name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '1.0.1'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Set version from manual input
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Setting version to: ${{ github.event.inputs.version }}"
        sed -i "s/ext.libVersion = '.*'/ext.libVersion = '${{ github.event.inputs.version }}'/" app/build.gradle
        
    - name: Set version from release tag
      if: github.event_name == 'release'
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        # Remove 'v' prefix if present (e.g., v1.2.3 -> 1.2.3)
        VERSION=${VERSION#v}
        echo "Setting version to: $VERSION"
        sed -i "s/ext.libVersion = '.*'/ext.libVersion = '$VERSION'/" app/build.gradle
        
    - name: Verify version was set
      run: |
        echo "Current version in build.gradle:"
        grep "ext.libVersion" app/build.gradle
        
    - name: Build library
      run: ./gradlew build
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Publish to Maven Central Portal
      run: ./gradlew publishAggregationToCentralPortal -PmavenCentralUsername="${{ secrets.MAVEN_CENTRAL_USERNAME }}" -PmavenCentralPassword="${{ secrets.MAVEN_CENTRAL_PASSWORD }}"
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-artifacts
        path: |
          app/build/outputs/aar/
          app/build/libs/
          app/build/publications/
        retention-days: 30